[package]
name = "filter_positions"
version = "0.1.0"
authors = ["Gianmarco Garrisi <gianmarcogarrisi@tutanota.com>"]

[dependencies]
serde_derive = "1"
serde_json="1"
serde = "1"
quicli = "0.3"
chrono = {version = "0.4", features =  ["serde"]}
rayon = "1"